logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:

knowledgeOut:
  properties:
    - property:
        type: "data"
        name: "laser_scan"
        class: "laser_scan"
        topic: "/laser_scan"
        QoS: 10

eventIn:
  properties:
    - property:
        type: "event"
        name: "new_model"
        class: "-"
        topic: "/Scan"
        QoS: 10

eventOut:
  properties:
    - property:
        type: "ship_status"
        name: "ship_status"
        class: "-"
        topic: "/new_data"
        QoS: 10
    - property:
        type: "weather_condition"
        name: "weather_condition"
        class: "-"
        topic: "/new_data"
        QoS: 10


mqtt_broker: "localhost"
mqtt_port: 1883

# mqtt_subscribe_topics:
#   - "ship_status"
#   - "weather_condition"

# mqtt_publish_topics:
#   - "/new_model"
#   - "/anomaly"

redis_host: "localhost"
redis_port: 6379

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "MAPE_ManagedSystem.log"

knowledge_config:
  storage_type: "global"
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0