# Docker Compose file to run an MQTT broker and the MQTT publisher
version: '3.10'

services:

  monitor:
    build:
        context: ./../../Nodes/Monitor
        dockerfile: ./Dockerfile
    container_name: C_Monitor

  analysis:
    build:
        context: ./../../Nodes/Analysis
        dockerfile: ./Dockerfile
    container_name: C_Analysis


networks:
  emqx-net:
    name: emqx-net