logger:
  endpoints:
    - endpoint:
        type: "logging"
        name: "RemoteLog"
        class: "LogMessage"
        topic: "/RemoteLog"
        QoS: 10

knowledgeIn:
  properties:

knowledgeOut:
  properties:
    - property:
        type: "data"
        name: "new_plan"
        class: "new_plan"
        topic: "/new_plan"
        QoS: 10
    - property:
        type: "data"
        name: "direction"
        class: "direction"
        topic: "/direction"
        QoS: 10

eventIn:
  properties:
    - property:
        type: "event"
        name: "start_m"
        class: "-"
        topic: "/rv/start_m"
        QoS: 10
    - property:
        type: "event"
        name: "start_a"
        class: "-"
        topic: "/rv/start_a"
        QoS: 10
    - property:
        type: "event"
        name: "start_p"
        class: "-"
        topic: "/rv/start_p"
        QoS: 10
    - property:
        type: "event"
        name: "start_l"
        class: "-"
        topic: "/rv/start_l"
        QoS: 10
    - property:
        type: "event"
        name: "start_e"
        class: "-"
        topic: "/rv/start_e"
        QoS: 10
    - property:
        type: "event"
        name: "/Scan"
        class: "-"
        topic: "/Scan"
        QoS: 10
    - property:
        type: "event"
        name: "new_data"
        class: "-"
        topic: "/new_data"
        QoS: 10
    - property:
        type: "event"
        name: "anomaly"
        class: "-"
        topic: "/anomaly"
        QoS: 10
    - property:
        type: "event"
        name: "no_anomaly"
        class: "-"
        topic: "/no_anomaly"
        QoS: 10
    - property:
        type: "event"
        name: "new_plan"
        class: "-"
        topic: "/new_plan"
        QoS: 10
    - property:
        type: "event"
        name: "isLegit"
        class: "-"
        topic: "/isLegit"
        QoS: 10
    - property:
        type: "event"
        name: "/spin_config"
        class: "-"
        topic: "/spin_config"
        QoS: 10
    - property:
        type: "event"
        name: "maple"
        class: "-"
        topic: "/maple"
        QoS: 10
    - property:
        type: "event"
        name: "k_laser_scan"
        class: "-"
        topic: "k_laser_scan"
        QoS: 10


eventOut:
  properties:
    - property:
        type: "stage"
        name: "stage"
        class: "-"
        topic: "stage"
        QoS: 10
    - property:
        type: "stage"
        name: "stage2"
        class: "-"
        topic: "stage2"
        QoS: 10
    - property:
        type: "event"
        name: "laser_scan"
        class: "-"
        topic: "k_laser_scan"
        QoS: 10
    - property:
        type: "event"
        name: "test_a"
        class: "-"
        topic: "k_a"
        QoS: 10


mqtt_broker: "localhost"
mqtt_port: 1883

mqtt_subscribe_topics:
  - "/Scan"
  - "/new_data"
  - "/anomaly"
  - "/new_plan"
  - "/isLegit"
  - "/spin_config"
  - "/maple"

mqtt_publish_topics:
  - "/stage"

redis_host: "localhost"
redis_port: 6379

logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "MAPE_test.log"

knowledge_config:
  storage_type: "global"
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0