

services:
  emqx-enterprise:
    image: emqx/emqx-enterprise:5.0.4
    container_name: emqx
    healthcheck:
      test: [ "CMD", "emqx", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 12
    ports:
      - 1883:1883
      - 18083:18083
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  maple-k:
    build: 
      context: ./ManagingSystem
      dockerfile: ./Dockerfile
    container_name: maple
    network_mode: "host"	
    environment:
      - MQTT_BROKER = "localhost"
      - REDIS_HOST = "localhost"	
    depends_on:
      emqx-enterprise:
          condition: service_healthy
    ports:
      - 8050:8050

#  rosmqttbridge:
#    build:
#      context: ./Bridge
#      dockerfile: Dockerfile.simple
#    container_name: bridge
#    network_mode: "host"
#    depends_on:
#      emqx-enterprise:
#          condition: service_healthy
#
    
  # simulator:
  #   build: 
  #     context: ./ManagedSystem
  #     dockerfile: ./Dockerfile
  #   container_name: turtle_simulator
  #   network_mode: "host"
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ENV_VAR=example
